### ISSUE TITLE
unable to install houndmind

### ISSUE THREAD

**Issue by joebiwankenobi** [seven-lynx/HoundMind#2]
hi @seven-lynx 

I've done a fresh install of the RPi OS (Trixie LITE 64 bit)  - if this needs to be Bookworm then please let me know.

I've updated and upgraded the RPi and enabled I2C & SPI in the config and rebooted.
Pulled your repository and proceeded to run

bash scripts/install_houndmind.sh (also tried bash scripts/install_houndmind.sh --preset full

it enables the .venv and starts the install but the after a few seconds errors with the following:

joe@PiDog:~/HoundMind $ bash scripts/install_houndmind.sh
+ /home/joe/HoundMind/.venv/bin/pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in ./.venv/lib/python3.13/site-packages (25.3)
Detected platform: pi4. Using preset: full.
+ /home/joe/HoundMind/.venv/bin/pip install -r /home/joe/HoundMind/requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement pidog>=0.1.0 (from versions: none)
ERROR: No matching distribution found for pidog>=0.1.0

I'm going to try the "manual" install guide and will update you of the outcome.

Kind Regards

Joe

 

re-formatted SD Card and installed "bookworm" LITE

still fails the install:

joe@PiDog:~/HoundMind $ bash scripts/install_houndmind.sh
+ /usr/bin/python3 -m venv /home/joe/HoundMind/.venv
+ /home/joe/HoundMind/.venv/bin/pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in ./.venv/lib/python3.11/site-packages (23.0.1)
Collecting pip
  Downloading https://www.piwheels.org/simple/pip/pip-25.3-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.7 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-25.3
Detected platform: pi4. Using preset: full.
+ /home/joe/HoundMind/.venv/bin/pip install -r /home/joe/HoundMind/requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement pidog>=0.1.0 (from versions: none)
ERROR: No matching distribution found for pidog>=0.1.0

**Comment by seven-lynx** [comment]
That's a shame, glad you got it sorted. It seems like parts always fail in the middle of the night. For me it was my PSU last month.

As for this, it appears there are no prebuilt wheels at all for RTAB-Map, or any other SLAM backend that would be useful to the pidog. I've been building and installing the package myself during testing, but I was hoping I wouldn't have to include this as a step for the installer. 

I've only taken a quick look, but as far as I can tell you are encountering 2 issues:

>>Python mismatch: The venv shown in your log used Python 3.11, and pip skipped many package versions that require <3.11 (see pip output: “Ignored the following versions that require a different python version…”).

>>No wheel for RTAB‑Map: rtabmap-py is not published as a usable wheel for Pi4/aarch64+modern Python, so pip reports “Could not find a version that satisfies the requirement rtabmap-py”.

What I changed (fix)

Installer enhancement: I updated the installer at pidog_install.py to:
Add a --build-rtabmap flag (and auto-enable building on Pi4 + full preset).
Create a temporary requirements file that excludes rtabmap-py so pip install -r does not fail.
Optionally install system packages (via apt) when building.
After pip installs, clone RTAB‑Map, run cmake/make/sudo make install, and install the Python bindings into the same environment.
Files touched: pidog_install.py. The original RTAB‑Map build notes remain in install_rtabmap_pi4.md.
How to re-run the installer now

I recommend you use a Python 3.10 interpreter for the venv if available (best compatibility). I'm updating the docs to clarify how and why.

To let the installer install system deps and build RTAB‑Map automatically on a Pi4:
`bash scripts/install_houndmind.sh --build-rtabmap --auto-system-deps`

Or run the underlying installer directly:
`python3 scripts/pidog_install.py --build-rtabmap --auto-system-deps`

To skip RTAB-Map install completely:
`bash scripts/install_houndmind.sh --no -rtabmap`

Skipping it is fine for now, the vision-based SLAM feature is far from complete anyway. When I have SLAM working I will most likely build a wheel and upload it to PyPi so users don't have to do this step with every install.

Building RTAB‑Map on a Pi4 can take 1–2 hours and requires build tools, disk space, and root privileges for sudo make install.
If the build fails, the installer will continue but SLAM will be unavailable (the code falls back to a stub). You can always follow install_rtabmap_pi4.md to debug manual builds.
This change avoids the pip error you saw; it does not produce prebuilt wheels — it builds RTAB‑Map from source into your environment. I'll have to put my pi4 board back into my pidog to test this, but I'll post an update here afterwards.

**Comment by joebiwankenobi** [comment]
[support.zip](https://github.com/user-attachments/files/24790857/support.zip)

hi @seven-lynx 

I have attached the support bundle you asked for - i hope it helps.

The LED Chest piece does work, when the program starts it is a CYAN colour, then as he starts to wander it flips between GREEN & RED

The head does track from left to right when he's walking about, but i have noticed there is no tail movement (this may be by design due to stability while walking but i thought i'd mention it)

I've re-pulled the repo and ran the setup installer again, the "cmake" is still present during the last stages of the install:



-- Could NOT find g2o (missing: g2o_DIR)
-- RTAB-Map's cmake g2o find module used for convenience (for older g2o versions)
CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (CSPARSE)
  does not match the name of the calling package (G2O).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake_modules/FindG2O.cmake:9 (find_package_handle_standard_args)
  CMakeLists.txt:518 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find CSPARSE (missing: CSPARSE_INCLUDE_DIR CSPARSE_LIBRARY)
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
-- GTSAM with NoiseModelFactorN.h
-- FlyCapture2_INCLUDE_DIR=FlyCapture2_INCLUDE_DIR-NOTFOUND


&


--   With VINS-Fusion          = NO (WITH_VINS_FUSION=OFF)
--   With OpenVINS             = NO (WITH_OPENVINS=OFF)
--   With ORB_SLAM             = NO (WITH_ORB_SLAM=OFF)
--   With cuVSLAM              = NO (WITH_CUVSLAM=OFF)
-- Show all options with: cmake -LA | grep WITH_
-- --------------------------------------------
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_EXECUTABLE


-- Build files have been written to: /home/joe/HoundMind/.cache/houndmind_deps/rtabmap/build
+ make -j 4
[  2%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UEventsHandler.cpp.o
[  2%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UEventsManager.cpp.o
[  2%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UEventsSender.cpp.o
[  2%] Building CXX object utilite/src/CMakeFiles/rtabmap_utilite.dir/UFile.cpp.o

  

the install run this time was a lot longer as it seems to be pulling a lot more packages and installing (which is a good thing as this is making the install a much more hassle free experience)

interestingly, a large part of the install is for the "rtabmap" install and setup , yet when the installer completes, it says :
rtabmap-py: MISSING (No module named 'rtabmap')
Installer check: FAILED

I've attached a TXT file of the complete install - it may help.

[install log.txt](https://github.com/user-attachments/files/24792484/install.log.txt)

Kind Regards 

Joe

**Comment by joebiwankenobi** [comment]
after the re-pull and install, i ran "python -m houndmind_ai"
the program launched and i see a FAIL on "sound_effect init"
PiDog moved his head left and right a few times then the program quit:


[launch quit.txt](https://github.com/user-attachments/files/24793253/launch.quit.txt)

[support.zip](https://github.com/user-attachments/files/24793257/support.zip)



.venv) joe@PiDog:~/HoundMind $ pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: numpy in /home/joe/.venv/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (2.4.1)
Collecting scipy (from -r requirements.txt (line 10))
  Using cached scipy-1.17.0-cp311-cp311-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl.metadata (62 kB)
Collecting opencv-contrib-python (from -r requirements.txt (line 15))
  Using cached opencv_contrib_python-4.13.0.90-cp37-abi3-manylinux_2_28_aarch64.whl.metadata (19 kB)
Collecting face_recognition (from -r requirements.txt (line 16))
  Using cached https://www.piwheels.org/simple/face-recognition/face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)
Collecting SpeechRecognition (from -r requirements.txt (line 19))
  Using cached https://www.piwheels.org/simple/speechrecognition/speechrecognition-3.14.5-py3-none-any.whl (32.9 MB)
Requirement already satisfied: pyaudio in /home/joe/.venv/lib/python3.11/site-packages (from -r requirements.txt (line 20)) (0.2.14)
Collecting sounddevice (from -r requirements.txt (line 21))
  Using cached sounddevice-0.5.4-py3-none-any.whl.metadata (1.4 kB)
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement rtabmap-py (from versions: none)
ERROR: No matching distribution found for rtabmap-py


i'll keep working on the python versions as a quick search says that the code has been built using "RPi OS Bullseye"
seems there are a few clashes between versions of Python being used.

Joe



P.S. - just re-reading your home page to see if i've missed anything new you may have added.
i did get an error yesterday when installing the SunFounder libraries

they now suggest using "pip install":

cd ~/
git clone -b 2.5.x https://github.com/sunfounder/robot-hat.git --depth 1
cd robot-hat
sudo python3 install.py

cd ~/
git clone https://github.com/sunfounder/vilib.git
cd vilib
sudo pip3 install . --break-system-packages

cd ~/
git clone https://github.com/sunfounder/pidog.git --depth 1
cd pidog
sudo pip3 install . --break

cd ~/robot-hat
sudo bash i2samp.sh


to get round some of the Python issues, (SunFounder requires 3.11 whereas other modules require 3.10)
i've changed the following file:
/HoundMind/.venv/lib/python3.10/site-packages/pidog/action_flow.py
from:
from enum import Enum, StrEnum
to:
from enum import Enum
try:
    from enum import StrEnum
except ImportError:
    class StrEnum(str, Enum):
        pass


PiDog is now moving again - but there are other issues to tackle now - Sound is still not working and:
 WARNING houndmind_ai.optional.vision_pi4: Picamera2 unavailable: No module named 'picamera2'
so just looking into getting that working

**Comment by Cpt-RegalBeagle** [comment]
having same issues as OP

Latest Bookworm Release
Python 3.10.16
Installed into venv

Sound_effect init failed
picamera2 module not found

I tried installing picamera2 via pip into the venv and it gets the the last package and fails:

Collecting python-prctl
  Using cached python-prctl-1.8.1.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      You need to install libcap development headers to build this module
      [end of output]

Cant seem to find a way to install these libcap development headers anywhere. Quick internet search seems to indicate that the modules are now baked into the OS itself, pip install perhaps unsupported?

I then burned my venv and started again with the --system-site-packages flag, hoping it would pick up what its missing from the system packages.

Just compiling the cmake steps currently 80% will report back.

**Comment by Cpt-RegalBeagle** [comment]
HoundMind installer verification
Python: 3.10 -> OK
numpy: OK
scipy: OK
opencv-contrib-python: OK
face_recognition: OK
SpeechRecognition: OK
pyaudio: OK
sounddevice: OK
rtabmap-py: MISSING (No module named 'rtabmap')
flask: OK
pidog: MISSING (cannot import name 'StrEnum' from 'enum' (/home/pidog/.pyenv/versions/3.10.16/lib/python3.10/enum.py))
houndmind_ai: OK
numpy: OK
scipy: OK
cv2: OK
face_recognition: OK
sounddevice: OK
Installer check: FAILED


PYTHON=python3.10 bash scripts/install_houndmind.sh --build-rtabmap --auto-system-deps --preset full

Getting the same StrEnum error as OP now. This worked OK on Python 3.11. rtabmap.py failing was expected.

Stumped now.

**Comment by Cpt-RegalBeagle** [comment]
After using OP workaround (I added the lines to dual_touch.py) and fiddling with indents (wasnt captured in chat.)

We have:

python -m tools.smoke_test
config_file: /home/pidog/.config/pidog/pidog.conf
robot_hat init ... done
imu_sh3001 init ... done
rgb_strip init ... done
dual_touch init ... done
sound_direction init ... done
sound_effect init ... fail
ultrasonic init ... done
Stopping and returning to the initial position ...
Quit
[smoke] sensor_reading: OK
[smoke] scan_latest: OK
[smoke] mapping_openings: OK
[smoke] PASS

No camera error..... sound init still fails.
